# Generated by Django 6.0.2 on 2026-02-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('path', models.TextField(blank=True, default='', null=True)),
                ('thumbnail_path', models.TextField(blank=True, default='', null=True)),
                ('show_path', models.TextField(blank=True, default='', null=True)),
                ('vendor', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('device', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shooting_time', models.DateTimeField(blank=True, null=True)),
                ('expo_time', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('iso', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('f_number', models.FloatField(blank=True, null=True)),
                ('equivalent_focal_length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('province', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('file_format', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('is_film', models.BooleanField(default=False)),
                ('film_model', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('formatted_name', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
