services:
  web:
    build: .
    image: photo-gallery:v1.0.2
    container_name: photo-gallery
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=PhotoGallery.settings
      - PRODUCTION=true