"""
Django settings for PhotoGallery project.

Generated by 'django-admin startproject' using Django 3.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-klr2ni($s918sb@69*ht9b076%pbec^1hc+38ok1xx#=!lt9x='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('PRODUCTION', 'false').lower() == 'false'

ALLOWED_HOSTS = ['huoyi.dynv6.net', 'www.huoyi.dynv6.net', 'localhost', '127.0.0.1']  # 加 www 如果你也想支持


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'PhotoInfo',
    'request',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'request.middleware.RequestMiddleware',
]

ROOT_URLCONF = 'PhotoGallery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PhotoGallery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_RELATIVE_PATH = os.path.join('data','dynamic')
MEDIA_ROOT = os.path.join(BASE_DIR,  MEDIA_RELATIVE_PATH)

SHOW_IMAGE_ROOT = os.path.join(MEDIA_ROOT, "photos", "show")
THUMBNAIL_IMAGE_ROOT = os.path.join(MEDIA_ROOT, "photos", "thumbnail")
UPLOADED_IMAGE_ROOT = os.path.join(MEDIA_ROOT, "uploaded")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-request 配置

# 忽略的路径（正则表达式，支持 re 语法）
# 注意：django-request 使用 request.path[1:]，所以不需要开头的斜杠
REQUEST_IGNORE_PATHS = [
    r'^static/',              # 静态文件
    r'^media/',               # 用户上传文件
    r'^data/', 
    r'^admin/.*',             # admin 后台（可选，如果你想记录 admin 访问可以去掉）
    r'^@vite/.*',  # django-request 记录的请求（可选，根据需要保留）
    r'^favicon\.ico$',
    r'^robots\.txt$',
    r'^__debug__/',           # 如果用了 django-debug-toolbar
]

# 忽略特定 User-Agent（爬虫、监控工具等）
REQUEST_IGNORE_USER_AGENTS = [
    'bot', 'spider', 'crawler',
    'Googlebot', 'Bingbot', 'Slurp',
    'Python-urllib', 'requests',
]

# HTTPS 相关（Caddy 会设置 X-Forwarded-Proto）
# 通过环境变量 PRODUCTION 来控制是否启用生产环境安全设置
PRODUCTION = os.environ.get('PRODUCTION', 'false').lower() == 'true'

if PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True          # 自动把 HTTP 请求重定向到 HTTPS（推荐开）
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    # 开发环境，禁用 HTTPS 强制重定向
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

from PhotoGallery.common import Static

Static.ensure_path_directories_exist()
